### ISSUE TITLE
BCML Will Not Run

### ISSUE THREAD

**Issue by xprsse** [NiceneNerd/BCML#292] opened 2022-04-01 01:22 UTC
For a while now I've been trying to get BCML to run, but I get this error when I run it:

Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\lib\site-packages\bcml\__main__.py", line 163, in <module>
    main()
  File "C:\Python38\lib\site-packages\bcml\__main__.py", line 60, in main
    util.parse_arguments()
AttributeError: module 'bcml.util' has no attribute 'parse_arguments'

When I first tried to install BCML I used Python 3.10 (because I use other programs that require python) and I got that error, and proceeded to uninstall 3.10, install 3.8 and put it on my path, then install BCML with --no-cache-dir. After doing that I still get the same error. Is there a way I can fix this?

**Comment by GingerAvalanche** [comment] 2022-04-01 01:27
Duplicate of #291. Find solution there

**Closed** 2022-04-01 01:43 UTC
