### ISSUE TITLE
Crashes during remerge

### ISSUE THREAD

**Issue by rehtlaw** [NiceneNerd/BCML#316] opened 2022-05-01 14:49 UTC
BCML crashes during a remerge or when I try to add a mod. It seems like it doesn't get to creating a new graphics pack, since I can't find one in Cemu. I'm using the AUR version and this is the output that I get from the cli:

```
❯ bcml
[pywebview] closing event is deprecated and will be removed in 4.0. Use events.closing instead
/usr/include/c++/11.2.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>; std::vector<_Tp, _Alloc>::reference = unsigned char&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
fish: Job 1, 'bcml' terminated by signal SIGABRT (Abort)
```

**Comment by h4rl0ck48** [comment] 2022-05-01 17:26
Im using the pip version and i can add and remerge mods fine. All tho the reorder part is broken.

**Comment by GingerAvalanche** [comment] 2022-05-01 21:47
I've seen that warning when using py310, but normally it doesn't cause any problems - it's just a deprecation notice, the problem that normally crops up is that bcml's dependencies don't work on py310. Dunno what python version you're using, but bcml's dependencies (and therefore bcml) are only compatible with py37, py38, and py39

That's not your problem, regardless. The warning message is for a closing event, which means when the main window closes. Something else is closing the window (probably your crash) and then the log is getting that warning as a side effect.

Not sure what to do here, since bcml has a ridiculous amount of error handling designed to tell you what the problem is, instead of crashing, so without more info I wouldn't know where to look.

**Comment by rehtlaw** [comment] 2022-05-02 00:30
any way to get a more verbose log out of bcml to get a chance of seeing what the actual problem is?
I should probably also note that there's a little bit of time between the last error/warning and it actually crashing, so I guess something else happens in the meantime.

Also idk if the AUR package uses another Python version somehow, but the regular OS version is 3.10.4

**Comment by GingerAvalanche** [comment] 2022-05-02 00:44
It would have to use a different version. As I mentioned, bcml's dependencies aren't compatible with minor versions above py39 (python 3.9, in less lazy terms). I didn't think it'd even install on py310, but I've never tried so I dunno.

Try `bcml-debug` or `py -m bcml` - the former runs in react logging mode, the latter runs in python logging mode. I don't *think* you can run `py -m bcml-debug` to get both, but you can try.

**Comment by rehtlaw** [comment] 2022-05-02 00:54
`python -m bcml-debug` does indeed not exist
`bcml-debug` didn't show anything new, just some generic react setup messages
and `python -m bcml` has the exact same output as my initial message

**Comment by h4rl0ck48** [comment] 2022-05-02 10:13
You can use pyenv to manage different python versions. Setup py38 for bcml and leave py310 for everything else. Also make sure u have install pyGObject. (Pacman -S gobject-introspection, and then pip install pyGObject)

this solves the mod installation and the remerge issue. At least for me.  Once again I did not used the AUR version. The one thing it doesn’t solve is the reorder func. Dunno why.

**Comment by AgentOtter** [comment] 2022-05-03 23:40
I'm having this same issue. Was prompted there was an update about an hour ago and now the app won't load. I have rebooted PC and done a repair install on python 3.8.8 and issue persists.
Also tried deleting all files from _pycache_ folder

```
C:\Users\ADMIN\AppData\Local\Programs\Python\Python38\Scripts>bcml-debug.exe
[CEF Python] ExceptHook: catched exception, will shutdown CEF

Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\admin\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python38\Scripts\bcml-debug.exe\__main__.py", line 7, in <module>
    sys.exit(main_debug())
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\bcml\__main__.py", line 158, in main_debug
    main(True)
  File "c:\users\admin\appdata\local\programs\python\python38\lib\site-packages\bcml\__main__.py", line 144, in main
    api.window.events.closing += stop_it
AttributeError: 'Window' object has no attribute 'events'
```

**Comment by GingerAvalanche** [comment] 2022-05-04 00:47
AgentOtter, see the linked issue. Apparently fixing the webview renderer broke the cef renderer. Yay.

**Comment by rehtlaw** [comment] 2022-05-05 05:43
> @AgentOtter see the linked issue. Apparently fixing the webview renderer broke the cef renderer. Yay.
> 
> @rehtlaw see if the new version does anything for you. That warning has been taken care of.

I guess I'll need to completely reinstall, since BCML still completely kills the desktop every time the window closes. (Although I didn't have that issue when I reported this issue, but it came back trying to update yesterday)

**Comment by GingerAvalanche** [comment] 2022-05-05 11:12
I have no better suggestions. Unless you can get one of the debug modes to spit something useful out, I don't know where I'd begin looking.

**Comment by rehtlaw** [comment] 2022-05-05 21:12
Alright, installed the latest update now and tried to remerge again, but I end up with the same error as before. Tried running bcml while I had set my global python version to 3.8.13 with pyenv, with no effect. Also tried installing bcml via pipx, which just resulted in a white window.

**Comment by GingerAvalanche** [comment] 2022-05-05 22:35
Dunno if this would help on linux, but on Windows a white window means you need to install `cefpython3` (linux should have that installed by default, but maybe your pipx doesn't have access to it or something)

**Comment by rehtlaw** [comment] 2022-05-06 07:50
> Dunno if this would help on linux, but on Windows a white window means you need to install `cefpython3` (linux should have that installed by default, but maybe your pipx doesn't have access to it or something)

I had the same issue when I tried installing it using regular pip as well, but I'll give it a try.

**Comment by NiceneNerd** [comment] 2022-05-06 15:18
`pywebview` doesn't support CEF on Linux

**Closed** 2022-06-01 17:55 UTC
