### ISSUE TITLE
BCML Hook crashes BOTW - not any mod installed

### ISSUE THREAD

**Issue by Haduken731** [NiceneNerd/BCML#46] opened 2020-04-30 08:54 UTC
BOTW crashes after compiling shaders, no matter if i have any mods installed or not, the graphics pack hook from BCML is preventing the gameplay - because after disabling the hook, the game runs fine.
Any ideas?

**Comment by NiceneNerd** [comment] 2020-05-04 15:09
Two questions:
(1) Have you tired remerge?
(2) Do you have any other mods (not counting the community graphic packs) installed by means other than BCML?

**Comment by Haduken731** [comment] 2020-05-04 17:06
Hey,
1) yeah
2) no
Also the 1.18.2c update of cemu fixed my general crashing, but i still cant play with mods.

**Comment by NiceneNerd** [comment] 2020-05-26 14:03
I can't reproduce this, and it doesn't seem to be happening to others who have everything properly configured. Closing for now.

**Closed** 2020-05-26 14:04 UTC
