### ISSUE TITLE
Problems running bcml 

### ISSUE THREAD

**Issue by jameshop2102** [NiceneNerd/BCML#373] opened 2022-06-27 20:05 UTC
I am having an issue where after I run bcml nothing happens, in my cmd I run bcml, and get the hourglass and nothing else. 
I ran this on bcml-debug.exe to try and see what's happening.  

Any suggestions would be greatly apricated, I am really excited to use your program.

[pywebview] Using WinForms / CEF

DevTools listening on ws://127.0.0.1:61269/devtools/browser/0ab23940-7572-4cba-8803-d5416bc8e739

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Control.get_CacheTextInternal()
   at System.Windows.Forms.Control.get_Text()
   at System.Windows.Forms.Control.set_Text(String value)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.Dispatcher.TrueDispatch(Object[] args)
   at Python.Runtime.Dispatcher.Dispatch(Object[] args)
   at __System_Threading_ThreadStartDispatcher.Invoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by NiceneNerd** [comment] 2022-06-27 20:10
Duplicate of #372

**Closed by NiceneNerd** 2022-06-27 20:10 UTC
