### ISSUE TITLE
3.2.3 fails to remerge- same config was fine with 3.2.2!

### ISSUE THREAD

**Issue by AeliusSaionji** [NiceneNerd/BCML#103] opened 2021-01-04 02:11 UTC
```
Traceback (most recent call last):
  File "C:\Users\aelius\AppData\Local\bcml\pkgs\bcml\_api.py", line 457, in remerge
    install.refresh_merges()
  File "C:\Users\aelius\AppData\Local\bcml\pkgs\bcml\install.py", line 561, in refresh_merges
    merger.perform_merge()
  File "C:\Users\aelius\AppData\Local\bcml\pkgs\bcml\util.py", line 461, in timed_function
    res = func(*args, **kwargs)
  File "C:\Users\aelius\AppData\Local\bcml\pkgs\bcml\mergers\texts.py", line 463, in perform_merge
    f"There was an error merging game texts. {result.stderr}"
RuntimeError: There was an error merging game texts. an error occurred - see below for details

could not read valid json from C:\Users\aelius\AppData\Local\Temp\tmpkioiu8jv\refs\USes\EventFlowMsg\MiniGame_Crosscountry.msyt
  invalid unicode code point at line 1 column 114


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\aelius\AppData\Local\bcml\pkgs\bcml\_api.py", line 30, in status_run
    data = func(*args, **kwargs)
  File "C:\Users\aelius\AppData\Local\bcml\pkgs\bcml\install.py", line 271, in do_and_refresh
    res = func(*args, **kwargs)
  File "C:\Users\aelius\AppData\Local\bcml\pkgs\bcml\_api.py", line 466, in remerge
    f"There was an error merging your mods. {str(err)}\n"
Exception: There was an error merging your mods. There was an error merging game texts. an error occurred - see below for details

could not read valid json from C:\Users\aelius\AppData\Local\Temp\tmpkioiu8jv\refs\USes\EventFlowMsg\MiniGame_Crosscountry.msyt
  invalid unicode code point at line 1 column 114

Note that this could leave your game in an unplayable state.
```

![image](https://user-images.githubusercontent.com/4342746/103495239-1b521080-4e08-11eb-8182-f40ad88703f1.png)

**Comment by NiceneNerd** [comment] 2021-01-04 02:58
Duplicate of #101

**Closed** 2021-01-04 02:58 UTC
