### ISSUE TITLE
Program terminated with signal SIGILL, Illegal instruction

### ISSUE THREAD

**Issue by eku** [NiceneNerd/BCML#440] opened 2022-10-30 13:27 UTC
Loading BOTW Mod Pack failes with SIGILL.

```
$ pip list
Package            Version
------------------ -----------
aamp               1.4.1
bcml               3.9.26
botw-havok         0.3.18
botw-utils         0.2.3
byml               2.4.2
certifi            2022.9.24
charset-normalizer 2.0.12
colorama           0.4.6
idna               3.4
numpy              1.19.5
oead               1.2.4.post2
packaging          21.3
pip                21.2.3
proxy-tools        0.1.0
pyparsing          3.0.9
PyQt5              5.15.7
PyQt5-Qt5          5.15.2
PyQt5-sip          12.11.0
PyQtWebEngine      5.15.6
PyQtWebEngine-Qt5  5.15.2
pywebview          3.6.3
PyYAML             5.4.1
QtPy               2.2.1
requests           2.27.1
rstb               1.2.2
setuptools         57.4.0
sortedcontainers   2.4.0
urllib3            1.26.12
wheel              0.36.2
xxhash             1.4.4
```

```
Core was generated by `/home/spiele/botw/bin/python /home/spiele/botw/bin/bcml'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x00007fc161c47455 in ?? () from /home/spiele/botw/lib64/python3.8/site-packages/bcml/bcml.cpython-38-x86_64-linux-gnu.so
[Current thread is 1 (Thread 0x7fc0ea050640 (LWP 197672))]
```

Please let me know if you need further information.

**Comment by GingerAvalanche** [comment] 2022-10-30 20:08
Hrm. This one's new. Try running with the command `bcml-debug`. Share the console output toward the end, starting from where it says `VERBOSEMerger packs, [some number] of [some larger number]` and all the way until it gives the error.

**Comment by NiceneNerd** [comment] 2022-11-01 18:30
With an error like that it's probably not traceable, even with debugging. But it's possible to try by setting up to build from source.

**Comment by GingerAvalanche** [comment] 2022-11-02 08:37
Error is happening between the log lines `Refreshing merged mods...` in `refresh_merges()` in install.py and `Loading modded SARC list...` in `PackMerger.perform_merge()` in pack.py.

No idea what could be causing the error there, as all 10-12 lines of bcml code that are between those two log lines are reused code that has been run successfully at least twice already, before you get to the stage of installation that you're at.

I suspect it might be something with the multiprocessing pool, as I can't imagine any of the pure python failing that harshly, but I could be wrong. Can't help much more than that, as I'm purely on Windows and can't reproduce.

**Comment by eku** [comment] 2022-11-24 09:54
@NiceneNerd wrote
> With an error like that it's probably not traceable, even with debugging. But it's possible to try by setting up to build from source.

Why do you think it is not tracable when we get a readable stack backtrace?

Do we have a container build environment like other projects do? I don't want to pollute my production system with the build environment installation.

**Comment by qgwoelk** [comment] 2022-12-01 07:18
I get what i believe to be a SIGLL error right about here, if this helps. also don't know why.

Merging 1342 SARC files...
Illegal instruction (core dumped)

**Comment by NiceneNerd** [comment] 2022-12-07 15:13
Going to go ahead and close this as a duplicate of #436

**Closed by NiceneNerd** 2022-12-07 15:13 UTC
