### ISSUE TITLE
export mods error

### ISSUE THREAD

**Issue by roobdog293000** [NiceneNerd/BCML#403] opened 2022-07-25 14:55 UTC
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\bcml\_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\bcml\_api.py", line 630, in export
    install.export(output)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\bcml\install.py", line 816, in export
    raise RuntimeError(
RuntimeError: There was an error exporting your mod(s). 
WARNING: The system cannot find the path specified.
C:\Users\User\AppData\Local\Temp\tmp4dwmd2nc\

**Comment by NiceneNerd** [comment] 2022-07-25 15:29
What in tarnation? I thought I literally just fixed that. What version do you have?

**Comment by Alkohole** [comment] 2022-07-30 11:11
Hello @NiceneNerd, I have the same problem when exporting.
BCML version 3.9.22. The same thing happened on version 3.9.21

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\bcml\_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "c:\python38\lib\site-packages\bcml\_api.py", line 630, in export
    install.export(output)
  File "c:\python38\lib\site-packages\bcml\install.py", line 819, in export
    raise RuntimeError(
RuntimeError: There was an error exporting your mod(s). 
WARNING: ‘ЁбвҐ¬Ґ ­Ґ г¤ Ґвбп ­ ©вЁ гЄ § ­­л© Їгвм.
C:\Users\Ladya\AppData\Local\Temp\tmprc933tb2\

**Comment by NiceneNerd** [comment] 2022-07-30 12:08
Try disabling links in your BCML settings

**Comment by Alkohole** [comment] 2022-07-30 15:30
Something new, is there something wrong with the DLC specified in the settings?  I'm doing this for Switch.

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\bcml\_api.py", line 33, in status_run
    data = func(*args, **kwargs)
  File "c:\python38\lib\site-packages\bcml\_api.py", line 630, in export
    install.export(output)
  File "c:\python38\lib\site-packages\bcml\install.py", line 771, in export
    link_master_mod(tmp_dir)
  File "c:\python38\lib\site-packages\bcml\install.py", line 745, in link_master_mod
    rsext.manager.link_master_mod(str(output) if output else None)
RuntimeError: Failed to copy output DLC folder

Caused by:
    The system cannot find the specified path. (os error 3)

**Comment by GingerAvalanche** [comment] 2022-07-31 07:26
Interestingly obscure. Apparently none of your mods contain map files, which is rare these days. We'll put in a check to make sure there are dlc files to copy before trying to copy them.

That'll at least fix the merging behavior while `Disable links for master mod` is checked. That will be fixed in 3.9.24 - If you want to play immediately, you can try to check out a mod that has dlc map files.

The earlier bug is a known issue that we have plenty of precedent for, so I'll be closing this.

**Closed by GingerAvalanche** 2022-07-31 07:26 UTC
