### ISSUE TITLE
"neither cef nor edge webview2 2 is available"

### ISSUE THREAD

**Issue by Opallono** [NiceneNerd/BCML#231] opened 2021-12-18 23:01 UTC
Once installing BCML using "Pip" through Python, I type BCML into the command and I get this error message: 
"neither cef nor edge webview2 2 is available"
Having learning difficulties, I don't know what to do as I find this very hard and frustrating. 
I need some help. Thanks

**Comment by NiceneNerd** [comment] 2021-12-18 23:06
Duplicate of #230

**Closed by NiceneNerd** 2021-12-18 23:06 UTC
